linters:
  enable-all: true
  disable:
    - exhaustruct
    - exportloopref
    - funlen
linters-settings:
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/aws/aws-sdk-go-v2/aws
          - github.com/aws/aws-sdk-go-v2/config
          - github.com/aws/aws-sdk-go-v2/service/ecs
          - github.com/aws/aws-sdk-go-v2/service/secretsmanager
          - github.com/spf13/cobra
          - github.com/wakeful/image-shift/pkg/ecs
          - github.com/wakeful/image-shift/pkg/secretsmng
          - github.com/wakeful/image-shift/cmd/sub
